// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.FormResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "RomCom",
                            Director = "Gary Winick",
                            Edited = true,
                            LentTo = "Cami",
                            Notes = "My favorite romcom",
                            Rating = "PG-13",
                            Title = "13 Going on 30",
                            Year = "2004"
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Superhero",
                            Director = "Joss Whedon",
                            Edited = false,
                            LentTo = "Spencer",
                            Notes = "So funny",
                            Rating = "PG-13",
                            Title = "The Avengers",
                            Year = "2012"
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Disney",
                            Director = "Nathan Greno",
                            Edited = false,
                            LentTo = "Elena",
                            Notes = "Best Princess Movie",
                            Rating = "PG",
                            Title = "Tangled",
                            Year = "2010"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
